### ISSUE TITLE
Where is the "config.h" file ?

### ISSUE THREAD

**Issue by dorald** [hana/ofxVboRenderer#12]
As title says this file is missing. You need to cleanup your code before push to master.

**Comment by hana** [comment]
@dorald Hi dorald, sorry about that and thank you for mentioning about this. I've just pushed the changes (I renamed config.h to VboRendererConfig.h) that I'd forgotten to do. Please let me know if you have any other troubles.

**Comment by dorald** [comment]
ok, I replace all with "VboRendererConfig.h". But I got another error on "VboCircleRenderer". You have declared this < void setLineWidth(float w); > function in "VboCircleRenderer.hpp" but isn't defined inside cpp class.

**Comment by hana** [comment]
Hopefully this commit would fix the issue!
